<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: stream.proto

namespace GPBMetadata;

class Stream
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            "\x0A\xED\x04\x0A\x0Cstream.proto\x12\x1Bcom.databrew.gateway.stream\"*\x0A\x0CAcceptCursor\x12\x0E\x0A\x06cursor\x18\x01 \x01(\x03\x12\x0A\x0A\x02id\x18\x02 \x01(\x09\"1\x0A\x0EAcceptedCursor\x12\x0E\x0A\x06cursor\x18\x01 \x01(\x03\x12\x0F\x0A\x07success\x18\x02 \x01(\x08\"-\x0A\x0DStreamRequest\x12\x0A\x0A\x02id\x18\x01 \x01(\x09\x12\x10\x0A\x08auto_ack\x18\x02 \x01(\x08\"\x9F\x01\x0A\x0EStreamResponse\x12\x13\x0A\x0Bexternal_pk\x18\x01 \x01(\x09\x12\x0B\x0A\x03raw\x18\x02 \x01(\x09\x12\x12\x0A\x0Acatalog_id\x18\x03 \x01(\x05\x12\x0E\x0A\x06source\x18\x04 \x01(\x09\x12\x14\x0A\x0Csource_event\x18\x05 \x01(\x09\x12\x10\x0A\x08data_set\x18\x06 \x01(\x09\x12\x0F\x0A\x07deleted\x18\x07 \x01(\x08\x12\x0E\x0A\x06cursor\x18\x08 \x01(\x032\xD9\x01\x0A\x06Stream\x12h\x0A\x09GetStream\x12*.com.databrew.gateway.stream.StreamRequest\x1A+.com.databrew.gateway.stream.StreamResponse\"\x000\x01\x12e\x0A\x09AckOffset\x12).com.databrew.gateway.stream.AcceptCursor\x1A+.com.databrew.gateway.stream.AcceptedCursor\"\x00B,Z*github.com/usedatabrew/datagateway/gen;genb\x06proto3"
        , true);

        static::$is_initialized = true;
    }
}

