<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: stream.proto

namespace Com\Databrew\Gateway\Stream;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>com.databrew.gateway.stream.AcceptCursor</code>
 */
class AcceptCursor extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int64 cursor = 1;</code>
     */
    protected $cursor = 0;
    /**
     * Generated from protobuf field <code>string id = 2;</code>
     */
    protected $id = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $cursor
     *     @type string $id
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Stream::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int64 cursor = 1;</code>
     * @return int|string
     */
    public function getCursor()
    {
        return $this->cursor;
    }

    /**
     * Generated from protobuf field <code>int64 cursor = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setCursor($var)
    {
        GPBUtil::checkInt64($var);
        $this->cursor = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string id = 2;</code>
     * @return string
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Generated from protobuf field <code>string id = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkString($var, True);
        $this->id = $var;

        return $this;
    }

}

