<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: stream.proto

namespace Com\Databrew\Gateway\Stream;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>com.databrew.gateway.stream.AcceptedCursor</code>
 */
class AcceptedCursor extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int64 cursor = 1;</code>
     */
    protected $cursor = 0;
    /**
     * Generated from protobuf field <code>bool success = 2;</code>
     */
    protected $success = false;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $cursor
     *     @type bool $success
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Stream::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int64 cursor = 1;</code>
     * @return int|string
     */
    public function getCursor()
    {
        return $this->cursor;
    }

    /**
     * Generated from protobuf field <code>int64 cursor = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setCursor($var)
    {
        GPBUtil::checkInt64($var);
        $this->cursor = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool success = 2;</code>
     * @return bool
     */
    public function getSuccess()
    {
        return $this->success;
    }

    /**
     * Generated from protobuf field <code>bool success = 2;</code>
     * @param bool $var
     * @return $this
     */
    public function setSuccess($var)
    {
        GPBUtil::checkBool($var);
        $this->success = $var;

        return $this;
    }

}

