<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: stream.proto

namespace Com\Databrew\Gateway\Stream;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>com.databrew.gateway.stream.StreamResponse</code>
 */
class StreamResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string external_pk = 1;</code>
     */
    protected $external_pk = '';
    /**
     * Generated from protobuf field <code>string raw = 2;</code>
     */
    protected $raw = '';
    /**
     * Generated from protobuf field <code>int32 catalog_id = 3;</code>
     */
    protected $catalog_id = 0;
    /**
     * Generated from protobuf field <code>string source = 4;</code>
     */
    protected $source = '';
    /**
     * Generated from protobuf field <code>string source_event = 5;</code>
     */
    protected $source_event = '';
    /**
     * Generated from protobuf field <code>string data_set = 6;</code>
     */
    protected $data_set = '';
    /**
     * Generated from protobuf field <code>bool deleted = 7;</code>
     */
    protected $deleted = false;
    /**
     * Generated from protobuf field <code>int64 cursor = 8;</code>
     */
    protected $cursor = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $external_pk
     *     @type string $raw
     *     @type int $catalog_id
     *     @type string $source
     *     @type string $source_event
     *     @type string $data_set
     *     @type bool $deleted
     *     @type int|string $cursor
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Stream::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string external_pk = 1;</code>
     * @return string
     */
    public function getExternalPk()
    {
        return $this->external_pk;
    }

    /**
     * Generated from protobuf field <code>string external_pk = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setExternalPk($var)
    {
        GPBUtil::checkString($var, True);
        $this->external_pk = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string raw = 2;</code>
     * @return string
     */
    public function getRaw()
    {
        return $this->raw;
    }

    /**
     * Generated from protobuf field <code>string raw = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setRaw($var)
    {
        GPBUtil::checkString($var, True);
        $this->raw = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 catalog_id = 3;</code>
     * @return int
     */
    public function getCatalogId()
    {
        return $this->catalog_id;
    }

    /**
     * Generated from protobuf field <code>int32 catalog_id = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setCatalogId($var)
    {
        GPBUtil::checkInt32($var);
        $this->catalog_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string source = 4;</code>
     * @return string
     */
    public function getSource()
    {
        return $this->source;
    }

    /**
     * Generated from protobuf field <code>string source = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setSource($var)
    {
        GPBUtil::checkString($var, True);
        $this->source = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string source_event = 5;</code>
     * @return string
     */
    public function getSourceEvent()
    {
        return $this->source_event;
    }

    /**
     * Generated from protobuf field <code>string source_event = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setSourceEvent($var)
    {
        GPBUtil::checkString($var, True);
        $this->source_event = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string data_set = 6;</code>
     * @return string
     */
    public function getDataSet()
    {
        return $this->data_set;
    }

    /**
     * Generated from protobuf field <code>string data_set = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setDataSet($var)
    {
        GPBUtil::checkString($var, True);
        $this->data_set = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool deleted = 7;</code>
     * @return bool
     */
    public function getDeleted()
    {
        return $this->deleted;
    }

    /**
     * Generated from protobuf field <code>bool deleted = 7;</code>
     * @param bool $var
     * @return $this
     */
    public function setDeleted($var)
    {
        GPBUtil::checkBool($var);
        $this->deleted = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 cursor = 8;</code>
     * @return int|string
     */
    public function getCursor()
    {
        return $this->cursor;
    }

    /**
     * Generated from protobuf field <code>int64 cursor = 8;</code>
     * @param int|string $var
     * @return $this
     */
    public function setCursor($var)
    {
        GPBUtil::checkInt64($var);
        $this->cursor = $var;

        return $this;
    }

}

